# Generated by Django 5.1.2 on 2024-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pessoas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
