# Generated by Django 5.1.2 on 2024-10-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pessoa_cpf_pessoa_endereco_pessoa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
